### ISSUE TITLE
How to support freestyle 15x15 ?

### ISSUE THREAD

**Issue by Reginer** [MaciejKozarzewski/AlphaGomoku#11]
`info timeout_turn 2000`

The next step will far exceed 2000 milliseconds.

**Comment by MaciejKozarzewski** [comment]
Can you elaborate more on the problem? What commands did you send and what is the output?

**Comment by Reginer** [comment]
```
……

INFO timeout_turn 2000

BOARD
10,10,1
10,11,2
11,11,1
9,10,2
DONE

```
Most of the time , After 2 seconds , AlphaGomoku did not provide a result .

**Comment by MaciejKozarzewski** [comment]
In the configuration file, set "use_logging": true
Then do what is necessary to reproduce the problem and send here the logfile.

**Comment by Reginer** [comment]
Oh , no
```
Received : info timeout_turn 2000
Received : info rule 0
Received : board
Received : 7,7,2
Received : 6,6,1
Received : 6,7,2
Received : 7,8,1
Received : 5,7,2
Received : 8,7,1
Received : 4,7,2
Received : 3,7,1
Received : 4,6,2
Received : done
Answered : ERROR FREESTYLE rule is not supported on 15x15 board
Received : end
```

**Comment by Reginer** [comment]
![image](https://github.com/MaciejKozarzewski/AlphaGomoku/assets/12568257/3e9e517a-908d-452d-a998-cd000e97ab3f)
